language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - echo "Build"
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - echo "Tag"
  - docker tag udagram-reverseproxy toliv22/udagram-reverseproxy:v2
  - docker tag udagram-api-feed toliv22/udagram-api-feed:v2
  - docker tag udagram-api-user toliv22/udagram-api-user:v2
  - docker tag udagram-frontend toliv22/udagram-frontend:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker images
  - echo "Start pushing"
  - docker push toliv22/udagram-reverseproxy:v2
  - docker push toliv22/udagram-api-feed:v2
  - docker push toliv22/udagram-api-user:v2
  - docker push toliv22/udagram-frontend:v2