apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-deployment
  labels:
    app: reverseproxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - name: reverseproxy-node
          image: letruongvu233/udagram-reverseproxy:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "150m"
            limits:
              memory: "1024Mi"
              cpu: "300m"
          ports:
            - containerPort: 8080
